application: bobbysummerproject
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/img
  static_dir: static/img

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

